use [CoursSGBD]

/****** Object:  Table [dbo].[Etudiant]    Script Date: 06/11/2025 19:10:38 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Etudiant](
	[ETU_ID] [int] IDENTITY(1,1) NOT NULL,
	[ETU_NOM] [varchar](50) NOT NULL,
	[ETU_PRENOM] [varchar](50) NULL,
	[ETU_MATRICULE] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Etudiant] PRIMARY KEY CLUSTERED 
(
	[ETU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

/****** Object:  Table [dbo].[Kot]    Script Date: 06/11/2025 19:10:38 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Kot](
	[KOT_ID] [int] IDENTITY(1,1) NOT NULL,
	[KOT_NAME] [varchar](50) NOT NULL,
	[KOT_ETUD_ID] [int] NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[Kot]  WITH CHECK ADD  CONSTRAINT [FK_Kot_Etu] FOREIGN KEY([KOT_ETUD_ID])
REFERENCES [dbo].[Etudiant] ([ETU_ID])

ALTER TABLE [dbo].[Kot] CHECK CONSTRAINT [FK_Kot_Etu]

